### ISSUE TITLE
new logo/icon

### ISSUE THREAD

**Issue by luthfirangers** [joelwass/Android-BLE-Connect-Example#1]
Hi @joelwass , I am a graphic designer, I want to help others in graphic design.

After I review your project, your logo is just a crop photo on this project. Therefore I would like to contribute to this project by creating a more interesting new logo / icon

**Comment by joelwass** [comment]
Great! fork the repo and issue a pull request! This isn't an issue though, so i'll be closing this

**Comment by luthfirangers** [comment]
sorry..

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by luthfirangers** [comment]
sorry,

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?
